//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : InventoriCerdas
	/// Data Source    : (LocalDb)\MSSQLLocalDB
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class InventoriCerdasDB : LinqToDB.Data.DataConnection
	{
		public ITable<Kabel>          Kabel          { get { return this.GetTable<Kabel>(); } }
		public ITable<Satuan>         Satuan         { get { return this.GetTable<Satuan>(); } }
		public ITable<TransaksiKabel> TransaksiKabel { get { return this.GetTable<TransaksiKabel>(); } }

		public InventoriCerdasDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public InventoriCerdasDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Kabel")]
	public partial class Kabel
	{
		[Column(Length=50),  PrimaryKey,  NotNull] public string KabelId    { get; set; } // varchar(50)
		[Column(Length=20),               NotNull] public string Code       { get; set; } // varchar(20)
		[Column(Length=50),               NotNull] public string Nama       { get; set; } // varchar(50)
		[Column(Length=50),               NotNull] public string Ukuran     { get; set; } // varchar(50)
		[Column(Length=250),    Nullable         ] public string Keterangan { get; set; } // varchar(250)
	}

	[Table(Schema="dbo", Name="Satuan")]
	public partial class Satuan
	{
		[Column(          Length=50), PrimaryKey,  NotNull] public string SatuanId     { get; set; } // varchar(50)
		[Column("Satuan", Length=50),              NotNull] public string SatuanColumn { get; set; } // varchar(50)
		[Column(          Length=10),    Nullable         ] public string Keterangan   { get; set; } // nchar(10)
	}

	[Table(Schema="dbo", Name="TransaksiKabel")]
	public partial class TransaksiKabel
	{
		[Column,             PrimaryKey,  NotNull] public int       TransaksiKabelId { get; set; } // int
		[Column,                Nullable         ] public int?      KabelId          { get; set; } // int
		[Column(Length=50),     Nullable         ] public string    JenisTransaksi   { get; set; } // varchar(50)
		[Column,                Nullable         ] public DateTime? Tanggal          { get; set; } // datetime
		[Column,                Nullable         ] public int?      Jumlah           { get; set; } // int
		[Column(Length=50),     Nullable         ] public string    Satuan           { get; set; } // varchar(50)
		[Column(Length=250),    Nullable         ] public string    Keterangan       { get; set; } // varchar(250)
	}
}

#pragma warning restore 1591
